export const cuisineList = [
  "Breakfast",
  "Cafe",
  "Chaat Chapati",
  "Chinese",
  "Desserts",
  "Dinner",
  "Gujarati",
  "Healthy",
  "Indian",
  "Lunch",
  "Maharashtrian",
  "Namkeen",
  "Noodles",
  "North Indian",
  "Pasta",
  "Pizza",
  "Pani Puri",
  "Punjabi",
  "Salads",
  "Sandwich",
  "South Indian",
  "Soups",
  "Sweets",
];
